OZ-348: Alignment with new `eip-client` + rm properties in favor of env vars
ozone-his/ozone-distro pull request #30
Opened 2024-01-04 13:47 UTC by corneliouzbett

Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-348

This PR aligns this project with new `eip-client` after refactoring [here](https://github.com/ozone-his/eip-client/pull/23)

2024-01-04 14:28 UTC, rbuisson requested changes
Few comments but otherwise lgtm. Thanks @corneliouzbett .

2024-01-04 14:28 UTC, rbuisson commented on distro/pom.xml
> +            <phase>package</phase>
Could we do this before the `package` phase, maybe `prepare-package`?

2024-01-04 14:28 UTC, rbuisson commented on distro/pom.xml
> +            <id>Copy EIP Odoo OpenMRS routes in a temporary location</id>
Since you're copying now directly the JAR in the final folder, let's rename to: "Copy EIP Odoo OpenMRS JAR"

2024-01-04 14:28 UTC, rbuisson commented on distro/pom.xml
> +            <id>Copy EIP OpenMRS SENAITE routes to a temporary location</id>
Let's rename to "Copy EIP OpenMRS SENAITE JAR"

2024-01-04 14:28 UTC, rbuisson commented on distro/pom.xml
> +        <version>3.2.0</version>
👍🏻

2024-01-04 16:57 UTC, rbuisson approved these changes

2024-01-04 16:57 UTC, merged

2024-01-05 07:14 UTC, corneliouzbett commented
@rbuisson Merging this breaks `main`. It has to wait for others PR on `eip-client`, `eip-odoo-openmrs` and `eip-openmrs-senaite` to be merge first. Should we revert this?

2024-01-05 11:25 UTC, rbuisson commented
Oh sorry about that. I guess I rushed. Let me reset so to keep history clean.

2024-01-05 11:31 UTC, rbuisson commented
It's reverted. You might need to re-PR @corneliouzbett .